### ISSUE TITLE
Compilation issues with Ubuntu 20.04 and ROS Noetic

### ISSUE THREAD

**Issue by taihup** [irapkaist/file_player#7]
Hi! 
There are some compilations issues related with OpenCV 4.2 (delivered with Ubuntu 20.04)
Some headers are deprecated as `cv.h`

```
file_player/src/ROSThread.h:20:10: fatal error: opencv/cv.h: No such file or directory
   20 | #include <opencv/cv.h>
```

The same happen with #include `<opencv/highgui.h>`, it does not exist anymore in OpenCV 4.2

This is easy to fix just replacing the lines with:
```
#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>
```
Then I have to rename some OpenCV constant occurrences:
CV_LOAD_IMAGE_COLOR -> cv::IMREAD_COLOR
CV_LOAD_IMAGE_ANYDEPTH -> cv::IMREAD_ANYDEPTH

Furthermore, there are issues related with PCL too:

`pcl_config.h:7:4: error: #error PCL requires C++14 or above`

To fix this, I just add the following lines to the CMakeLists.txt file:

```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON) 
```

**Comment by taihup** [comment]
I just see the PR proposed here: #6

**Comment by JinXJinLeX** [comment]
exchange:
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
